# Generated by Django 6.0.6 on 2026-06-24 10:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_ref', models.CharField(db_index=True, max_length=50, unique=True)),
                ('wallet_address', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_data', models.JSONField(default=dict)),
                ('data_hash', models.CharField(db_index=True, max_length=66)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('blockchain_status', models.CharField(default='NOT_SUBMITTED', max_length=50)),
                ('verification_status', models.CharField(default='NOT_VERIFIED', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HASHED', 'Hashed'), ('BLOCKCHAIN_PENDING', 'Blockchain Pending'), ('BLOCKCHAIN_CONFIRMED', 'Blockchain Confirmed'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='HASHED', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'form_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'form_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(default='LOCAL_HARDHAT', max_length=100)),
                ('contract_address', models.CharField(blank=True, max_length=100, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transaction', to='submissions.formsubmission')),
            ],
            options={
                'db_table': 'blockchain_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='submissions.formtemplate'),
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_hash', models.CharField(max_length=66)),
                ('blockchain_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('result', models.CharField(choices=[('MATCHED', 'Matched'), ('MISMATCHED', 'Mismatched'), ('NOT_FOUND', 'Not Found'), ('ERROR', 'Error')], max_length=30)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='submissions.formsubmission')),
            ],
            options={
                'db_table': 'verification_logs',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('key', models.SlugField(max_length=255)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('NUMBER', 'Number'), ('TEXTAREA', 'Textarea'), ('SELECT', 'Select'), ('CHECKBOX', 'Checkbox'), ('RADIO', 'Radio'), ('DATE', 'Date')], default='TEXT', max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='submissions.formtemplate')),
            ],
            options={
                'db_table': 'form_fields',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('form', 'key')},
            },
        ),
    ]
